### ISSUE TITLE
[Meta] Download feature refactoring

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1563]
This is a follow up to #1554:

This is what needs to be done to the download feature (as explained [here](https://github.com/iv-org/invidious/issues/1554#issuecomment-741041928)):

- [ ] Move everything related to download to its own file (ping @matthewmcgarvey ) > Cleaner code

- [ ] Put the whole download UI in a `<detail>` (idea and existing implementation by @julianfoad [here](https://gitlab.com/julianfoad/invidious/-/commit/893f1c466a0f2394121809ed29aaaaa8a003a856)) > Cleaner UI

- [ ] Make download disabled by default > No more bandwidth speed waste on instances that aren't configured completely

- [ ] Remove the message displayed when download is disabled > Cleaner UI

- [ ] Stop proxying downloads, download from googlevideo > No more bandwidth speed waste

- [ ] Remove the ability to disable download on certain video ID (IE: download is all or nothing) > Simpler code

- [ ] Only display: the best audio only opus - the audio only aac > Simpler UI + Cleaner UI

- [ ] If enabled with a (new) setting also display: the 360p video+audio - the 720p video+audio

**Comment by Seneral** [comment]
Pretty sure this is known, but some videos (namely those with licensed music) can only be downloaded by the IP that fetched the page, so downloading them directly on the client wouldn't work in that case. Unless you know something I don't, in which case I'm interested, I made a [client-side youtube player](https://github.com/Seneral/FlagPlayer) that can currently only play videos with licensed music when using a local cors host, which kinda defeats the point.

**Comment by saltycrys** [comment]
The UI is in `src/invidious/views/watch.ecr`: https://github.com/iv-org/invidious/blob/ba148d749f3f3b745704c35bde2f72ea194b1ddb/src/invidious/views/watch.ecr#L136-L170

It is a form that points to `/latest_version` which is in `src/invidious.cr`: https://github.com/iv-org/invidious/blob/ba148d749f3f3b745704c35bde2f72ea194b1ddb/src/invidious.cr#L3362-L3408

`/latest_version` then redirects to `/videoplayback` to do the actual downloading.

As it is implemented right now this is always proxied. This is hardcoded and cannot be overridden: https://github.com/iv-org/invidious/blob/ba148d749f3f3b745704c35bde2f72ea194b1ddb/src/invidious.cr#L3376

<hr>

The ability to disable downloads of certain videos is handled by the `dmca_content` config option: https://github.com/iv-org/invidious/blob/ba148d749f3f3b745704c35bde2f72ea194b1ddb/src/invidious/views/watch.ecr#L136-L138

This is defined in `src/invidious/helpers/helpers.cr`: https://github.com/iv-org/invidious/blob/ba148d749f3f3b745704c35bde2f72ea194b1ddb/src/invidious/helpers/helpers.cr#L86

`src/invidious/helpers/helpers.cr` is also the place to add new config options. Adding and removing them can be done safely and without breaking existing configs as long as any additions are either nillable or have a default value set.

**Comment by ckorder** [comment]
@TheFrenchGhosty  please pin again, due to the fact that we want people to use youtube as less as possible. or do you wanna waste more of their bandwidth ? 😄 I'm looking forward to the fact that a hero will show up and provide a solution in 2021

**Comment by NintendoManiac64** [comment]
Minor suggestion regarding audio-only downloads - how realistic would it be to have them use the extensions .MKA and .M4A instead? (for reference, youtube-dl uses the .M4A extension for AAC audio, though it uses .WEBM for OPUS audio).

In my experience, even with media players that are very picky about the extension matching the format (e.g. foobar2000), simply renaming a .WEBM to .MKA as well as renaming a .MP4 to .M4A will still result in it working without any issue.

Or are the extensions determined by YouTube's servers and therefore cannot be changed?

**Comment by NintendoManiac64** [comment]
> Stop proxying downloads, download from googlevideo > No more bandwidth speed waste

What about videos that are only available when using the proxy?

For example I'm in the US, and the following video is not available in the US but in available in France:
https://www.youtube.com/watch?v=cQXkRbjQw1w

This therefore means that, when the invidious proxy setting is enabled, I'm able to watch it through a French invidious instance such as yewtu.be:
https://yewtu.be/watch?v=7qPsMTCuqUQ&local=true

And because the downloads are also proxied currently I can sucessfully download.  But if the proxy function is removed completely then that goes out the window and instead forced the user to do a right-click -> "save as" on the video itself.

**Comment by SamantazFox** [comment]
Update:

> * Move everything related to download to its own file

Done in #2922 and #3087 (I've updated the original message)

> * Put the whole download UI in a `<detail>` > Cleaner UI

I don't think we should implement this. The ui needs to be entirely reworked.

> - Make download disabled by default
> - Remove the message displayed when download is disabled > Cleaner UI

Yes, to be done !

>  Stop proxying downloads, download from googlevideo

Nope! Nope! Nope!
Downloads already respect the `local` parameter, that's all we need.

> Remove the ability to disable download on certain video ID

Already done, a long time ago. I don't remember in which PR.

> Only display: the best audio only opus - the audio only aac

To be discussed, but imho it's not useful, as it will require more code to select the "best" qualities...

> If enabled with a (new) setting also display: the 360p video+audio - the 720p video+audio

??? All formats are already displayed.
