### ISSUE TITLE
[Meta] Footer complete refactor

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2032]
The Invidious footer needs to be redone almost completely.

- [] https://github.com/iv-org/invidious/issues/2022 needs to be fixed
- [] It needs to be reordered properly,
- [] It shouldn't mention omarroth
- [] It must link to the AGPL text on the GNU website
- [] It should link to invidious.io
- [] It should link to https://github.com/iv-org
- [] The privacy policy page must be entirely deprecated/removed, and it should just link to [URL].EXT/privacy (that admins are supposed to override in their reverse proxy, in the same way I do for my Bibliogram instance: https://github.com/PussTheCat-org/PussTheCat.org-Configs/blob/master/Nginx/sites-available/bibliogram.pussthecat.org.conf#L25)
- [] An about page must be created, in this about page should be contained the admin Github profile and a way to contact them (preferably email)
- [] Donations option must be moved to invidious.io/donate (it needs to be created https://github.com/iv-org/invidious.io ) so that there's a *trusted* place to get them (other than the Github readme)
- More?

Super quick and dirty draft (it's missing the link to an about page / to the AGPL text on the GNU website):

![iv](https://user-images.githubusercontent.com/47571719/115577884-4d528a00-a2b4-11eb-83ed-ffcc20498876.png)

**Comment by unixfox** [comment]
What do you think of having the ability to add a contact the maintainer button like on Searx at the bottom of the page?

**Comment by TheFrenchGhosty** [comment]
@unixfox In the about page, as I said before, should be a lot better.

**Comment by unixfox** [comment]
> @unixfox In the about page, as I said before, should be a lot better. 

Why in a different page? It's much easier to have one button directly accessible.

**Comment by SamantazFox** [comment]
> Why in a different page? It's much easier to have one button directly accessible.

To not clutter too much the footer. There are already a lof of things in here, and this is more confusing than helping

**Comment by TheFrenchGhosty** [comment]
Yeah exactly, the footer should be as "simple" as possible.

**Comment by syeopite** [comment]
Whew finally found some time to work on this. 

Due to the massive amounts of items Invidious needs within the footer I don't think the current bar-like design would work very well. It looks too cramped. Instead I propose a footer block:

![2-1](https://user-images.githubusercontent.com/70992037/116781664-3b51b380-aa39-11eb-8ee6-3a671053c68e.png)

Of course this also means that the footer would be hidden from view unless scrolled to. I do think that's a worthy trade off though.

If we must preserve the current footer design then I think we should at least remove as much as possible. Something along the lines of this:
![1](https://user-images.githubusercontent.com/70992037/116781766-f5491f80-aa39-11eb-887b-2c100dc87b17.png)

**Comment by TheFrenchGhosty** [comment]
@syeopite The block is great.
