### ISSUE TITLE
[Meta] Overhaul Invidious player for more YT features.

### ISSUE THREAD

**Issue by syeopite** [iv-org/invidious#2395]
This is a meta-issue to track everything that needs to be done in order to fix the discrepancy between Invidious and YouTube's players

- [ ] End-cards
- [ ] Auto-generated captions (Follow up to: https://github.com/iv-org/invidious/issues/2187#issuecomment-866014531)
- [ ] Audio tracks (#2007)
- [ ] Channel Favicons 
- [ ] Custom playback speeds (#533)
- [ ]  Miniplayer (#583, #631)
- [ ] 3D 
- [ ] Frame-by-frame skipping (#2113),
- [ ] Fine scrubbing (mobile-only feature on YT)
- [ ] Chapters
- [ ] Theater mode? 
- [ ]  Related videos in full screen? (useful for embeds and binge watching.)

**Comment by AlexMiniReal** [comment]
Is someone working on the chapters enhancement?

**Comment by AlexMiniReal** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/76444133/143689087-25160c89-5369-4a9a-afd7-0e3a52c8c01b.jpg)

**Comment by unixfox** [comment]
> Is someone working on the chapters enhancement?

not that we know of

**Comment by debpalash** [comment]
I was waiting for the UI overhaul for so long until made a stylus css myself for player pages now it has full viewport width player and home. [repo here](https://github.com/debpalash/InvidiousFullScreen-Stylus)

**Comment by IronMaltese** [comment]
Is this able to be implemented in mainline invidious?

**Comment by debpalash** [comment]
i guess one could fork and inject my css 🤔

**Comment by arjun44** [comment]
@debpalash FYI: I forked your stylus css; I removed and simplified some things. It can be easily extended further. You can see the source [here](https://gist.github.com/arjun44/4700b1a629d0885a6dc564a3d67e6cca), it's very short.

**Comment by debpalash** [comment]
@arjun44 nice 😂 . btw you need this to work on stylus `@-moz-document url-prefix("https://instance.tld")`

**Comment by selurvedu** [comment]
I'm not seeing YouTube Cards support in the list (example [here](https://i.ytimg.com/vi/zQg3f-sVxiU/maxresdefault.jpg)). Is it planned?

**Comment by syeopite** [comment]
Added. Thank you
